### ISSUE TITLE
Plans for future additions?

### ISSUE THREAD

**Issue by Tarnxc8349** [Akrivus/StoKAGIC#1]
Hi,
I've added this to the wiki, but I'd like to know more about what exactly you plan on adding and removing.
Thanks!

**Comment by Akrivus** [comment]
Hello Tarnxc8349!
I respect the gesture of informing others about StoKAGIC on the KAGIC wiki, but I'd prefer that StoKAGIC and KAGIC's communities each live in separate planes of existence for the time being.
Thanks for your time, but I'll take the rest from here. :+1:
